name: Prebuild and publish (dev)

on:
  workflow_dispatch:
  push:
    tags:
      - 'dev*'

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            name: linux-x64
          - os: windows-latest
            name: win32-x64
          - os: macos-14
            name: darwin-arm64
          - os: macos-13
            name: darwin-x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python (for node-gyp)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: npm ci

      - name: Build prebuilds (N-API)
        run: npm run prebuild

      - name: Upload prebuild artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuilds-${{ matrix.name }}
          path: prebuilds/**

  publish:
    name: Publish to npm (dev tag)
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/dev')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Download all prebuild artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: prebuilds-*
          merge-multiple: true
          path: ./

      - name: List bundled prebuilds
        run: |
          echo "Prebuilds content:";
          ls -R prebuilds || true

      - name: Publish with dev tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag dev


